<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
		<OutputPath>$(SolutionDir)\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Image\לוגו גדול.jpg" />
	  <None Remove="Image\תמונה של מתנדבים.jpg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BL\BL.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Image\לוגו גדול.jpg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Image\תמונה של מתנדבים.jpg">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>