<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
		<OutputPath>$(SolutionDir)\bin\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<UseCommonOutputDirectory>true</UseCommonOutputDirectory>
		<RootNamespace />
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="$(NuGetPackageRoot)system.text.json\9.0.0\lib\net8.0\System.Text.Json.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DalFacade\DalFacade.csproj" />
		<ProjectReference Include="..\DalList\DalList.csproj" />
		<ProjectReference Include="..\DalTest\DalTest.csproj" />
		<ProjectReference Include="..\DalXml\DalXml.csproj" />
	</ItemGroup>

</Project>
